In [1]:
#loading a data
import numpy as np
import pandas as pd

In [2]:
#Read data
df=pd.read_csv(r"C:\Users\varun\Downloads\anime.csv")

In [3]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [4]:
#Questions:
#make a new column for episode count
#make a new column for time stamp
#which anime has the highest score
#give me top 5 highest scoring anime
#which anime has the highest episode count
#animes with top 5 episode count

In [5]:
#1
#make a new column for episode count:

In [6]:
df.loc[8]["Title"]

'Kaguya-sama wa Kokurasetai: Ultra RomanticTV (13 eps)Apr 2022 - Jun 2022851,445 members'

In [7]:
#Function for extracting the episodes:
def extract_episodes(text):
    check=False
    data=""
    for i in text:
        if i==")":
            check=False
            break
        if check==True:
            data+=i
        if i=="(":
            check=True

    return data

In [8]:
df["episodes"]=df["Title"].apply(extract_episodes)

In [9]:
df.head(3)

   Rank                                              Title  Score episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps

In [10]:
df["episodes"]=df["episodes"].str.replace(" eps","")

In [11]:
df.head(3)

   Rank                                              Title  Score episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Rank      50 non-null     int64
 1   Title     50 non-null     object
 2   Score     50 non-null     float64
 3   episodes  50 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 1.7+ KB

In [13]:
df["episodes"]=df["episodes"].astype(int)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Rank      50 non-null     int64
 1   Title     50 non-null     object
 2   Score     50 non-null     float64
 3   episodes  50 non-null     int32
dtypes: float64(1), int32(1), int64(1), object(1)
memory usage: 1.5+ KB

In [15]:
#2
#make a new column for time stamp:

In [16]:
df.loc[4]["Title"]

'Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview'

In [17]:
#function for extracting time stamp:
def extract_timestamp(text):
    check=False
    data=""

    for i in range(len(text)):
        if text[i]==",":
            check=False
            break
            
        if text[i] == ")":
            check=True
            if check==True:
                j=i+1
                while j<i+20:
                    data+=text[j]
                    j+=1
    return data

In [18]:
df["Time_Stamp"]=df["Title"].apply(extract_timestamp)

In [19]:
df.head()

,Rank,Title,Score,episodes,Time_Stamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [20]:
#3
#which anime has the highest score

In [35]:
df[["Title","Score"]].loc[[df["Score"].idxmax()]]

                                               Title  Score
0  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...    9.1

In [24]:
#4
#give me top 5 highest scoring anime

In [32]:
df.sort_values("Score",ascending=False).head()[["Title","Score"]]

                                               Title  Score
0  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [28]:
#5
#which anime has the highest episode count

In [31]:
df.sort_values("episodes",ascending=False).head(1)[["Title","episodes"]]

                                                Title  episodes
15  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...       201

In [36]:
#6
#animes with top 5 episode count

In [37]:
df.sort_values("episodes",ascending=False).head()[["Title","episodes"]]

                                                Title  episodes
15  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...       201
7   Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...       148
11  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...       110
42  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...        75
24  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...        74